spring:
  application:
    name: demothithujava6_5
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PTPM_FINALLY_SOF306;encrypt=true;trustServerCertificate=true;
    username: sq
    password: 123456789
  jpa:
    open-in-view: true
    show-sql: true
